//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 10:03:58 AM PKT 
//


package org.example;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbsLoanCreditScoreBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbsLoanCreditScoreBean">
 *   &lt;complexContent>
 *     &lt;extension base="{http://mobiliser.sybase365.com/custom/project/services/contract/v1_0/beans}BaseRequestBean">
 *       &lt;sequence>
 *         &lt;element name="fileNo" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="tranxNo" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="score" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="odds" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="probOfDefalut" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="percentileRisk" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="sbpRiskLevel" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbsLoanCreditScoreBean", propOrder = {
    "fileNo",
    "tranxNo",
    "score",
    "odds",
    "probOfDefalut",
    "percentileRisk",
    "sbpRiskLevel"
})
public class AbsLoanCreditScoreBean
    extends BaseRequestBean
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected long fileNo;
    protected long tranxNo;
    protected long score;
    @XmlElement(required = true)
    protected String odds;
    @XmlElement(required = true)
    protected String probOfDefalut;
    @XmlElement(required = true)
    protected String percentileRisk;
    @XmlElement(required = true)
    protected String sbpRiskLevel;

    /**
     * Gets the value of the fileNo property.
     * 
     */
    public long getFileNo() {
        return fileNo;
    }

    /**
     * Sets the value of the fileNo property.
     * 
     */
    public void setFileNo(long value) {
        this.fileNo = value;
    }

    /**
     * Gets the value of the tranxNo property.
     * 
     */
    public long getTranxNo() {
        return tranxNo;
    }

    /**
     * Sets the value of the tranxNo property.
     * 
     */
    public void setTranxNo(long value) {
        this.tranxNo = value;
    }

    /**
     * Gets the value of the score property.
     * 
     */
    public long getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     */
    public void setScore(long value) {
        this.score = value;
    }

    /**
     * Gets the value of the odds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOdds() {
        return odds;
    }

    /**
     * Sets the value of the odds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOdds(String value) {
        this.odds = value;
    }

    /**
     * Gets the value of the probOfDefalut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProbOfDefalut() {
        return probOfDefalut;
    }

    /**
     * Sets the value of the probOfDefalut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProbOfDefalut(String value) {
        this.probOfDefalut = value;
    }

    /**
     * Gets the value of the percentileRisk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercentileRisk() {
        return percentileRisk;
    }

    /**
     * Sets the value of the percentileRisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercentileRisk(String value) {
        this.percentileRisk = value;
    }

    /**
     * Gets the value of the sbpRiskLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSbpRiskLevel() {
        return sbpRiskLevel;
    }

    /**
     * Sets the value of the sbpRiskLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSbpRiskLevel(String value) {
        this.sbpRiskLevel = value;
    }

}
