//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 10:03:58 AM PKT 
//


package org.example;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbsLoanCcpMasterBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbsLoanCcpMasterBean">
 *   &lt;complexContent>
 *     &lt;extension base="{http://mobiliser.sybase365.com/custom/project/services/contract/v1_0/beans}BaseRequestBean">
 *       &lt;sequence>
 *         &lt;element name="fileNo" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="tranxNo" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="loanNo" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="note" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="seqNo" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="memName" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="subbrnName" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="acctNo" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="acctTy" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="mappedAcctTy" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="term" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="acctStatus" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="limit" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="openDate" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="maturityDate" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="assocTy" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="groupId" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="statusDate" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="minAmtDue" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="bncChq" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="lastPayment" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="highCredit" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="overDueAmount" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="balance" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="paymentStatus" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="currency" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="relationDt" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="secure" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="paymentFreq" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="classCatg" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="subObj" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="loanClassDesc" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="rescheduleFlag" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="rescheduleDt" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="dispute" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbsLoanCcpMasterBean", propOrder = {
    "fileNo",
    "tranxNo",
    "loanNo",
    "note",
    "seqNo",
    "memName",
    "subbrnName",
    "acctNo",
    "acctTy",
    "mappedAcctTy",
    "term",
    "acctStatus",
    "limit",
    "openDate",
    "maturityDate",
    "assocTy",
    "groupId",
    "statusDate",
    "minAmtDue",
    "bncChq",
    "lastPayment",
    "highCredit",
    "overDueAmount",
    "balance",
    "paymentStatus",
    "currency",
    "relationDt",
    "secure",
    "paymentFreq",
    "classCatg",
    "subObj",
    "loanClassDesc",
    "rescheduleFlag",
    "rescheduleDt",
    "dispute"
})
public class AbsLoanCcpMasterBean
    extends BaseRequestBean
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected long fileNo;
    protected long tranxNo;
    protected long loanNo;
    @XmlElement(required = true)
    protected String note;
    protected long seqNo;
    @XmlElement(required = true)
    protected String memName;
    @XmlElement(required = true)
    protected String subbrnName;
    @XmlElement(required = true)
    protected String acctNo;
    @XmlElement(required = true)
    protected String acctTy;
    @XmlElement(required = true)
    protected String mappedAcctTy;
    @XmlElement(required = true)
    protected String term;
    @XmlElement(required = true)
    protected String acctStatus;
    protected long limit;
    @XmlElement(required = true)
    protected String openDate;
    @XmlElement(required = true)
    protected String maturityDate;
    @XmlElement(required = true)
    protected String assocTy;
    protected long groupId;
    protected long statusDate;
    protected long minAmtDue;
    protected long bncChq;
    protected long lastPayment;
    protected long highCredit;
    protected long overDueAmount;
    protected long balance;
    @XmlElement(required = true)
    protected String paymentStatus;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(required = true)
    protected String relationDt;
    @XmlElement(required = true)
    protected String secure;
    @XmlElement(required = true)
    protected String paymentFreq;
    @XmlElement(required = true)
    protected String classCatg;
    @XmlElement(required = true)
    protected String subObj;
    @XmlElement(required = true)
    protected String loanClassDesc;
    @XmlElement(required = true)
    protected String rescheduleFlag;
    @XmlElement(required = true)
    protected String rescheduleDt;
    @XmlElement(required = true)
    protected String dispute;

    /**
     * Gets the value of the fileNo property.
     * 
     */
    public long getFileNo() {
        return fileNo;
    }

    /**
     * Sets the value of the fileNo property.
     * 
     */
    public void setFileNo(long value) {
        this.fileNo = value;
    }

    /**
     * Gets the value of the tranxNo property.
     * 
     */
    public long getTranxNo() {
        return tranxNo;
    }

    /**
     * Sets the value of the tranxNo property.
     * 
     */
    public void setTranxNo(long value) {
        this.tranxNo = value;
    }

    /**
     * Gets the value of the loanNo property.
     * 
     */
    public long getLoanNo() {
        return loanNo;
    }

    /**
     * Sets the value of the loanNo property.
     * 
     */
    public void setLoanNo(long value) {
        this.loanNo = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the seqNo property.
     * 
     */
    public long getSeqNo() {
        return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     */
    public void setSeqNo(long value) {
        this.seqNo = value;
    }

    /**
     * Gets the value of the memName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemName() {
        return memName;
    }

    /**
     * Sets the value of the memName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemName(String value) {
        this.memName = value;
    }

    /**
     * Gets the value of the subbrnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubbrnName() {
        return subbrnName;
    }

    /**
     * Sets the value of the subbrnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubbrnName(String value) {
        this.subbrnName = value;
    }

    /**
     * Gets the value of the acctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * Sets the value of the acctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctNo(String value) {
        this.acctNo = value;
    }

    /**
     * Gets the value of the acctTy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctTy() {
        return acctTy;
    }

    /**
     * Sets the value of the acctTy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctTy(String value) {
        this.acctTy = value;
    }

    /**
     * Gets the value of the mappedAcctTy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMappedAcctTy() {
        return mappedAcctTy;
    }

    /**
     * Sets the value of the mappedAcctTy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMappedAcctTy(String value) {
        this.mappedAcctTy = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerm(String value) {
        this.term = value;
    }

    /**
     * Gets the value of the acctStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctStatus() {
        return acctStatus;
    }

    /**
     * Sets the value of the acctStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctStatus(String value) {
        this.acctStatus = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     */
    public long getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     */
    public void setLimit(long value) {
        this.limit = value;
    }

    /**
     * Gets the value of the openDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenDate() {
        return openDate;
    }

    /**
     * Sets the value of the openDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenDate(String value) {
        this.openDate = value;
    }

    /**
     * Gets the value of the maturityDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaturityDate() {
        return maturityDate;
    }

    /**
     * Sets the value of the maturityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaturityDate(String value) {
        this.maturityDate = value;
    }

    /**
     * Gets the value of the assocTy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssocTy() {
        return assocTy;
    }

    /**
     * Sets the value of the assocTy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssocTy(String value) {
        this.assocTy = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     */
    public long getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     */
    public void setGroupId(long value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the statusDate property.
     * 
     */
    public long getStatusDate() {
        return statusDate;
    }

    /**
     * Sets the value of the statusDate property.
     * 
     */
    public void setStatusDate(long value) {
        this.statusDate = value;
    }

    /**
     * Gets the value of the minAmtDue property.
     * 
     */
    public long getMinAmtDue() {
        return minAmtDue;
    }

    /**
     * Sets the value of the minAmtDue property.
     * 
     */
    public void setMinAmtDue(long value) {
        this.minAmtDue = value;
    }

    /**
     * Gets the value of the bncChq property.
     * 
     */
    public long getBncChq() {
        return bncChq;
    }

    /**
     * Sets the value of the bncChq property.
     * 
     */
    public void setBncChq(long value) {
        this.bncChq = value;
    }

    /**
     * Gets the value of the lastPayment property.
     * 
     */
    public long getLastPayment() {
        return lastPayment;
    }

    /**
     * Sets the value of the lastPayment property.
     * 
     */
    public void setLastPayment(long value) {
        this.lastPayment = value;
    }

    /**
     * Gets the value of the highCredit property.
     * 
     */
    public long getHighCredit() {
        return highCredit;
    }

    /**
     * Sets the value of the highCredit property.
     * 
     */
    public void setHighCredit(long value) {
        this.highCredit = value;
    }

    /**
     * Gets the value of the overDueAmount property.
     * 
     */
    public long getOverDueAmount() {
        return overDueAmount;
    }

    /**
     * Sets the value of the overDueAmount property.
     * 
     */
    public void setOverDueAmount(long value) {
        this.overDueAmount = value;
    }

    /**
     * Gets the value of the balance property.
     * 
     */
    public long getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     */
    public void setBalance(long value) {
        this.balance = value;
    }

    /**
     * Gets the value of the paymentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * Sets the value of the paymentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentStatus(String value) {
        this.paymentStatus = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the relationDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationDt() {
        return relationDt;
    }

    /**
     * Sets the value of the relationDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationDt(String value) {
        this.relationDt = value;
    }

    /**
     * Gets the value of the secure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecure() {
        return secure;
    }

    /**
     * Sets the value of the secure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecure(String value) {
        this.secure = value;
    }

    /**
     * Gets the value of the paymentFreq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentFreq() {
        return paymentFreq;
    }

    /**
     * Sets the value of the paymentFreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentFreq(String value) {
        this.paymentFreq = value;
    }

    /**
     * Gets the value of the classCatg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassCatg() {
        return classCatg;
    }

    /**
     * Sets the value of the classCatg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassCatg(String value) {
        this.classCatg = value;
    }

    /**
     * Gets the value of the subObj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubObj() {
        return subObj;
    }

    /**
     * Sets the value of the subObj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubObj(String value) {
        this.subObj = value;
    }

    /**
     * Gets the value of the loanClassDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanClassDesc() {
        return loanClassDesc;
    }

    /**
     * Sets the value of the loanClassDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanClassDesc(String value) {
        this.loanClassDesc = value;
    }

    /**
     * Gets the value of the rescheduleFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRescheduleFlag() {
        return rescheduleFlag;
    }

    /**
     * Sets the value of the rescheduleFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRescheduleFlag(String value) {
        this.rescheduleFlag = value;
    }

    /**
     * Gets the value of the rescheduleDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRescheduleDt() {
        return rescheduleDt;
    }

    /**
     * Sets the value of the rescheduleDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRescheduleDt(String value) {
        this.rescheduleDt = value;
    }

    /**
     * Gets the value of the dispute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispute() {
        return dispute;
    }

    /**
     * Sets the value of the dispute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispute(String value) {
        this.dispute = value;
    }

}
