//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 10:03:58 AM PKT 
//


package org.example;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AbsLoanCreditSummaryBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbsLoanCreditSummaryBean">
 *   &lt;complexContent>
 *     &lt;extension base="{http://mobiliser.sybase365.com/custom/project/services/contract/v1_0/beans}BaseRequestBean">
 *       &lt;sequence>
 *         &lt;element name="fileNo" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="tranxNo" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="category" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="name" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="cnic" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="fileCreationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="loanCount" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="loanLimit" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="loanOs" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="loanless10k" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="loneabove10k" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="current30Plus" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="closeWithinMaturity" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="closeAfterMaturity" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="defaultCount" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="defaultOs" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="month2430Plus" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="month2460Plus" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="month2490Plus" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="enquiryCount" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="associationCount" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbsLoanCreditSummaryBean", propOrder = {
    "fileNo",
    "tranxNo",
    "category",
    "name",
    "cnic",
    "fileCreationDate",
    "loanCount",
    "loanLimit",
    "loanOs",
    "loanless10K",
    "loneabove10K",
    "current30Plus",
    "closeWithinMaturity",
    "closeAfterMaturity",
    "defaultCount",
    "defaultOs",
    "month2430Plus",
    "month2460Plus",
    "month2490Plus",
    "enquiryCount",
    "associationCount"
})
public class AbsLoanCreditSummaryBean
    extends BaseRequestBean
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected long fileNo;
    protected long tranxNo;
    @XmlElement(required = true)
    protected String category;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String cnic;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fileCreationDate;
    protected long loanCount;
    protected long loanLimit;
    protected long loanOs;
    @XmlElement(name = "loanless10k")
    protected long loanless10K;
    @XmlElement(name = "loneabove10k")
    protected long loneabove10K;
    protected long current30Plus;
    protected long closeWithinMaturity;
    protected long closeAfterMaturity;
    protected long defaultCount;
    protected long defaultOs;
    protected long month2430Plus;
    protected long month2460Plus;
    protected long month2490Plus;
    protected long enquiryCount;
    @XmlElement(required = true)
    protected String associationCount;

    /**
     * Gets the value of the fileNo property.
     * 
     */
    public long getFileNo() {
        return fileNo;
    }

    /**
     * Sets the value of the fileNo property.
     * 
     */
    public void setFileNo(long value) {
        this.fileNo = value;
    }

    /**
     * Gets the value of the tranxNo property.
     * 
     */
    public long getTranxNo() {
        return tranxNo;
    }

    /**
     * Sets the value of the tranxNo property.
     * 
     */
    public void setTranxNo(long value) {
        this.tranxNo = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the cnic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnic() {
        return cnic;
    }

    /**
     * Sets the value of the cnic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnic(String value) {
        this.cnic = value;
    }

    /**
     * Gets the value of the fileCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFileCreationDate() {
        return fileCreationDate;
    }

    /**
     * Sets the value of the fileCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFileCreationDate(XMLGregorianCalendar value) {
        this.fileCreationDate = value;
    }

    /**
     * Gets the value of the loanCount property.
     * 
     */
    public long getLoanCount() {
        return loanCount;
    }

    /**
     * Sets the value of the loanCount property.
     * 
     */
    public void setLoanCount(long value) {
        this.loanCount = value;
    }

    /**
     * Gets the value of the loanLimit property.
     * 
     */
    public long getLoanLimit() {
        return loanLimit;
    }

    /**
     * Sets the value of the loanLimit property.
     * 
     */
    public void setLoanLimit(long value) {
        this.loanLimit = value;
    }

    /**
     * Gets the value of the loanOs property.
     * 
     */
    public long getLoanOs() {
        return loanOs;
    }

    /**
     * Sets the value of the loanOs property.
     * 
     */
    public void setLoanOs(long value) {
        this.loanOs = value;
    }

    /**
     * Gets the value of the loanless10K property.
     * 
     */
    public long getLoanless10K() {
        return loanless10K;
    }

    /**
     * Sets the value of the loanless10K property.
     * 
     */
    public void setLoanless10K(long value) {
        this.loanless10K = value;
    }

    /**
     * Gets the value of the loneabove10K property.
     * 
     */
    public long getLoneabove10K() {
        return loneabove10K;
    }

    /**
     * Sets the value of the loneabove10K property.
     * 
     */
    public void setLoneabove10K(long value) {
        this.loneabove10K = value;
    }

    /**
     * Gets the value of the current30Plus property.
     * 
     */
    public long getCurrent30Plus() {
        return current30Plus;
    }

    /**
     * Sets the value of the current30Plus property.
     * 
     */
    public void setCurrent30Plus(long value) {
        this.current30Plus = value;
    }

    /**
     * Gets the value of the closeWithinMaturity property.
     * 
     */
    public long getCloseWithinMaturity() {
        return closeWithinMaturity;
    }

    /**
     * Sets the value of the closeWithinMaturity property.
     * 
     */
    public void setCloseWithinMaturity(long value) {
        this.closeWithinMaturity = value;
    }

    /**
     * Gets the value of the closeAfterMaturity property.
     * 
     */
    public long getCloseAfterMaturity() {
        return closeAfterMaturity;
    }

    /**
     * Sets the value of the closeAfterMaturity property.
     * 
     */
    public void setCloseAfterMaturity(long value) {
        this.closeAfterMaturity = value;
    }

    /**
     * Gets the value of the defaultCount property.
     * 
     */
    public long getDefaultCount() {
        return defaultCount;
    }

    /**
     * Sets the value of the defaultCount property.
     * 
     */
    public void setDefaultCount(long value) {
        this.defaultCount = value;
    }

    /**
     * Gets the value of the defaultOs property.
     * 
     */
    public long getDefaultOs() {
        return defaultOs;
    }

    /**
     * Sets the value of the defaultOs property.
     * 
     */
    public void setDefaultOs(long value) {
        this.defaultOs = value;
    }

    /**
     * Gets the value of the month2430Plus property.
     * 
     */
    public long getMonth2430Plus() {
        return month2430Plus;
    }

    /**
     * Sets the value of the month2430Plus property.
     * 
     */
    public void setMonth2430Plus(long value) {
        this.month2430Plus = value;
    }

    /**
     * Gets the value of the month2460Plus property.
     * 
     */
    public long getMonth2460Plus() {
        return month2460Plus;
    }

    /**
     * Sets the value of the month2460Plus property.
     * 
     */
    public void setMonth2460Plus(long value) {
        this.month2460Plus = value;
    }

    /**
     * Gets the value of the month2490Plus property.
     * 
     */
    public long getMonth2490Plus() {
        return month2490Plus;
    }

    /**
     * Sets the value of the month2490Plus property.
     * 
     */
    public void setMonth2490Plus(long value) {
        this.month2490Plus = value;
    }

    /**
     * Gets the value of the enquiryCount property.
     * 
     */
    public long getEnquiryCount() {
        return enquiryCount;
    }

    /**
     * Sets the value of the enquiryCount property.
     * 
     */
    public void setEnquiryCount(long value) {
        this.enquiryCount = value;
    }

    /**
     * Gets the value of the associationCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociationCount() {
        return associationCount;
    }

    /**
     * Sets the value of the associationCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociationCount(String value) {
        this.associationCount = value;
    }

}
