//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 10:03:58 AM PKT 
//


package org.example;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AbsLoanDefaultsBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbsLoanDefaultsBean">
 *   &lt;complexContent>
 *     &lt;extension base="{http://mobiliser.sybase365.com/custom/project/services/contract/v1_0/beans}BaseRequestBean">
 *       &lt;sequence>
 *         &lt;element name="fileNo" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="tranxNo" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="loanNo" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="note" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="memName" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="subbrnName" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="relDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="orgStatusDate" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="orgAcctNo" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="orgAmount" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="orgAcctTy" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="orgMappedAcctTy" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="orgStatus" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="orgRtr" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="orgCurrency" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="updStatusDate" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="updAcctNo" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="updAcctNoStr" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="updAmount" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="updAcctTy" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="updMappedAcctTy" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="updStatus" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="updRtr" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="updCurrency" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="secure" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="classCatg" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="subObj" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="loanClassDesc" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="assosTy" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="groupId" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="recoveryAmount" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}idLong"/>
 *         &lt;element name="recoveryDate" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *         &lt;element name="dispute" type="{http://mobiliser.sybase365.com/framework/contract/v5_0/base}strMedium"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbsLoanDefaultsBean", propOrder = {
    "fileNo",
    "tranxNo",
    "loanNo",
    "note",
    "memName",
    "subbrnName",
    "relDt",
    "orgStatusDate",
    "orgAcctNo",
    "orgAmount",
    "orgAcctTy",
    "orgMappedAcctTy",
    "orgStatus",
    "orgRtr",
    "orgCurrency",
    "updStatusDate",
    "updAcctNo",
    "updAcctNoStr",
    "updAmount",
    "updAcctTy",
    "updMappedAcctTy",
    "updStatus",
    "updRtr",
    "updCurrency",
    "secure",
    "classCatg",
    "subObj",
    "loanClassDesc",
    "assosTy",
    "groupId",
    "recoveryAmount",
    "recoveryDate",
    "dispute"
})
public class AbsLoanDefaultsBean
    extends BaseRequestBean
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected long fileNo;
    protected long tranxNo;
    protected long loanNo;
    @XmlElement(required = true)
    protected String note;
    @XmlElement(required = true)
    protected String memName;
    @XmlElement(required = true)
    protected String subbrnName;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar relDt;
    @XmlElement(required = true)
    protected String orgStatusDate;
    @XmlElement(required = true)
    protected String orgAcctNo;
    protected long orgAmount;
    @XmlElement(required = true)
    protected String orgAcctTy;
    @XmlElement(required = true)
    protected String orgMappedAcctTy;
    @XmlElement(required = true)
    protected String orgStatus;
    @XmlElement(required = true)
    protected String orgRtr;
    @XmlElement(required = true)
    protected String orgCurrency;
    @XmlElement(required = true)
    protected String updStatusDate;
    protected long updAcctNo;
    @XmlElement(required = true)
    protected String updAcctNoStr;
    protected long updAmount;
    @XmlElement(required = true)
    protected String updAcctTy;
    @XmlElement(required = true)
    protected String updMappedAcctTy;
    @XmlElement(required = true)
    protected String updStatus;
    @XmlElement(required = true)
    protected String updRtr;
    @XmlElement(required = true)
    protected String updCurrency;
    @XmlElement(required = true)
    protected String secure;
    @XmlElement(required = true)
    protected String classCatg;
    @XmlElement(required = true)
    protected String subObj;
    @XmlElement(required = true)
    protected String loanClassDesc;
    @XmlElement(required = true)
    protected String assosTy;
    protected long groupId;
    protected long recoveryAmount;
    @XmlElement(required = true)
    protected String recoveryDate;
    @XmlElement(required = true)
    protected String dispute;

    /**
     * Gets the value of the fileNo property.
     * 
     */
    public long getFileNo() {
        return fileNo;
    }

    /**
     * Sets the value of the fileNo property.
     * 
     */
    public void setFileNo(long value) {
        this.fileNo = value;
    }

    /**
     * Gets the value of the tranxNo property.
     * 
     */
    public long getTranxNo() {
        return tranxNo;
    }

    /**
     * Sets the value of the tranxNo property.
     * 
     */
    public void setTranxNo(long value) {
        this.tranxNo = value;
    }

    /**
     * Gets the value of the loanNo property.
     * 
     */
    public long getLoanNo() {
        return loanNo;
    }

    /**
     * Sets the value of the loanNo property.
     * 
     */
    public void setLoanNo(long value) {
        this.loanNo = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the memName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemName() {
        return memName;
    }

    /**
     * Sets the value of the memName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemName(String value) {
        this.memName = value;
    }

    /**
     * Gets the value of the subbrnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubbrnName() {
        return subbrnName;
    }

    /**
     * Sets the value of the subbrnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubbrnName(String value) {
        this.subbrnName = value;
    }

    /**
     * Gets the value of the relDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRelDt() {
        return relDt;
    }

    /**
     * Sets the value of the relDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRelDt(XMLGregorianCalendar value) {
        this.relDt = value;
    }

    /**
     * Gets the value of the orgStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgStatusDate() {
        return orgStatusDate;
    }

    /**
     * Sets the value of the orgStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgStatusDate(String value) {
        this.orgStatusDate = value;
    }

    /**
     * Gets the value of the orgAcctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgAcctNo() {
        return orgAcctNo;
    }

    /**
     * Sets the value of the orgAcctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgAcctNo(String value) {
        this.orgAcctNo = value;
    }

    /**
     * Gets the value of the orgAmount property.
     * 
     */
    public long getOrgAmount() {
        return orgAmount;
    }

    /**
     * Sets the value of the orgAmount property.
     * 
     */
    public void setOrgAmount(long value) {
        this.orgAmount = value;
    }

    /**
     * Gets the value of the orgAcctTy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgAcctTy() {
        return orgAcctTy;
    }

    /**
     * Sets the value of the orgAcctTy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgAcctTy(String value) {
        this.orgAcctTy = value;
    }

    /**
     * Gets the value of the orgMappedAcctTy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgMappedAcctTy() {
        return orgMappedAcctTy;
    }

    /**
     * Sets the value of the orgMappedAcctTy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgMappedAcctTy(String value) {
        this.orgMappedAcctTy = value;
    }

    /**
     * Gets the value of the orgStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgStatus() {
        return orgStatus;
    }

    /**
     * Sets the value of the orgStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgStatus(String value) {
        this.orgStatus = value;
    }

    /**
     * Gets the value of the orgRtr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgRtr() {
        return orgRtr;
    }

    /**
     * Sets the value of the orgRtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgRtr(String value) {
        this.orgRtr = value;
    }

    /**
     * Gets the value of the orgCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgCurrency() {
        return orgCurrency;
    }

    /**
     * Sets the value of the orgCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgCurrency(String value) {
        this.orgCurrency = value;
    }

    /**
     * Gets the value of the updStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdStatusDate() {
        return updStatusDate;
    }

    /**
     * Sets the value of the updStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdStatusDate(String value) {
        this.updStatusDate = value;
    }

    /**
     * Gets the value of the updAcctNo property.
     * 
     */
    public long getUpdAcctNo() {
        return updAcctNo;
    }

    /**
     * Sets the value of the updAcctNo property.
     * 
     */
    public void setUpdAcctNo(long value) {
        this.updAcctNo = value;
    }

    /**
     * Gets the value of the updAcctNoStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdAcctNoStr() {
        return updAcctNoStr;
    }

    /**
     * Sets the value of the updAcctNoStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdAcctNoStr(String value) {
        this.updAcctNoStr = value;
    }

    /**
     * Gets the value of the updAmount property.
     * 
     */
    public long getUpdAmount() {
        return updAmount;
    }

    /**
     * Sets the value of the updAmount property.
     * 
     */
    public void setUpdAmount(long value) {
        this.updAmount = value;
    }

    /**
     * Gets the value of the updAcctTy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdAcctTy() {
        return updAcctTy;
    }

    /**
     * Sets the value of the updAcctTy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdAcctTy(String value) {
        this.updAcctTy = value;
    }

    /**
     * Gets the value of the updMappedAcctTy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdMappedAcctTy() {
        return updMappedAcctTy;
    }

    /**
     * Sets the value of the updMappedAcctTy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdMappedAcctTy(String value) {
        this.updMappedAcctTy = value;
    }

    /**
     * Gets the value of the updStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdStatus() {
        return updStatus;
    }

    /**
     * Sets the value of the updStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdStatus(String value) {
        this.updStatus = value;
    }

    /**
     * Gets the value of the updRtr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdRtr() {
        return updRtr;
    }

    /**
     * Sets the value of the updRtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdRtr(String value) {
        this.updRtr = value;
    }

    /**
     * Gets the value of the updCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdCurrency() {
        return updCurrency;
    }

    /**
     * Sets the value of the updCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdCurrency(String value) {
        this.updCurrency = value;
    }

    /**
     * Gets the value of the secure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecure() {
        return secure;
    }

    /**
     * Sets the value of the secure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecure(String value) {
        this.secure = value;
    }

    /**
     * Gets the value of the classCatg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassCatg() {
        return classCatg;
    }

    /**
     * Sets the value of the classCatg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassCatg(String value) {
        this.classCatg = value;
    }

    /**
     * Gets the value of the subObj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubObj() {
        return subObj;
    }

    /**
     * Sets the value of the subObj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubObj(String value) {
        this.subObj = value;
    }

    /**
     * Gets the value of the loanClassDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanClassDesc() {
        return loanClassDesc;
    }

    /**
     * Sets the value of the loanClassDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanClassDesc(String value) {
        this.loanClassDesc = value;
    }

    /**
     * Gets the value of the assosTy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssosTy() {
        return assosTy;
    }

    /**
     * Sets the value of the assosTy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssosTy(String value) {
        this.assosTy = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     */
    public long getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     */
    public void setGroupId(long value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the recoveryAmount property.
     * 
     */
    public long getRecoveryAmount() {
        return recoveryAmount;
    }

    /**
     * Sets the value of the recoveryAmount property.
     * 
     */
    public void setRecoveryAmount(long value) {
        this.recoveryAmount = value;
    }

    /**
     * Gets the value of the recoveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecoveryDate() {
        return recoveryDate;
    }

    /**
     * Sets the value of the recoveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecoveryDate(String value) {
        this.recoveryDate = value;
    }

    /**
     * Gets the value of the dispute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispute() {
        return dispute;
    }

    /**
     * Sets the value of the dispute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispute(String value) {
        this.dispute = value;
    }

}
